package UI;

import entities.Author;
import entities.Book;
import entities.BookType;
import entities.Item;
import entities.Tag;
import java.awt.Component;
import java.time.Year;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTextField;

public class AddBookUI extends UI {

    public AddBookUI(CardLayoutMain cardLayoutMain) {
        super(cardLayoutMain);
        initComponents();
        initJlist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        titleField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        locationField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        yearField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descField = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        barcodeField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ISBNField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bookTypeCombo = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        authorsList = new javax.swing.JList<Author>();
        jLabel10 = new javax.swing.JLabel();
        authorListCombo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        saveBookBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tagsListCombo = new javax.swing.JComboBox();
        addTagBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tagsList = new javax.swing.JList<Tag>();
        jLabel13 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Add new book");

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Title");

        jLabel3.setText("Location");

        jLabel4.setText("Relase year");

        yearField.setText("yyyy");

        jLabel5.setText("Description");

        descField.setColumns(20);
        descField.setRows(5);
        jScrollPane1.setViewportView(descField);

        jLabel6.setText("Barcode");

        jLabel7.setText("ISBN");

        jLabel9.setText("Book type");

        authorsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                authorsListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(authorsList);

        jLabel10.setText("Add authors");

        jButton1.setText("Add author");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Authors (double click to remove)");

        saveBookBtn.setText("Save book");
        saveBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBookBtnActionPerformed(evt);
            }
        });

        jLabel12.setText("Add tags");

        addTagBtn.setText("Add tag");
        addTagBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTagBtnActionPerformed(evt);
            }
        });

        tagsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tagsListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tagsList);

        jLabel13.setText("Tags (double click to remove)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cancelBtn)
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(saveBookBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(titleField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(locationField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(yearField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(barcodeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jButton1)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(authorListCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bookTypeCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ISBNField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(tagsListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addTagBtn)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cancelBtn)
                    .addComponent(saveBookBtn))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ISBNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagsListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(addTagBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authorListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void initJlist(){
        //Authors
        modelAuthor = new DefaultListModel<>();
        authorsList.setModel(modelAuthor);
        
        modelTags = new DefaultListModel<>();
        tagsList.setModel(modelTags);
    }
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.switchToCard(EmployeeStartUI.class);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        if(this.getCardLayoutMain().getEmpLoggedIn() == null){
            UI.showErrorDialog("Not logged in!");
            System.exit(1);
        }
        
        //Reset all fields (except dob)
        Component[] components = this.getComponents();
        for(Component currentComp : components){
            if(currentComp instanceof JTextField){
                JTextField field;
                field = (JTextField) currentComp;
                field.setText("");
            }     
        }
        descField.setText("");
        modelAuthor.removeAllElements();
        modelTags.removeAllElements();
        
        
        //Setup all Booktypes in comboBox
        List<BookType> bookTypes = this.getCardLayoutMain().getEntityManager().createNamedQuery("BookType.findAll")
                .getResultList();
        bookTypeCombo.removeAllItems();
        for(BookType current : bookTypes){
            bookTypeCombo.addItem(current);
        }
        
        //Setup all Authors in comboBox
        List<Author> authors = this.getCardLayoutMain().getEntityManager().createNamedQuery("Author.findAll")
                .getResultList();
        authorListCombo.removeAllItems();
        for(Author current : authors){
            authorListCombo.addItem(current);
        }
        
        //Setup all Tags in comboBox
        List<Tag> tags = this.getCardLayoutMain().getEntityManager().createNamedQuery("Tag.findAll")
                .getResultList();
        tagsListCombo.removeAllItems();
        for(Tag curr : tags){
            tagsListCombo.addItem(curr);
        }
        
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Author selAuthor = (Author) authorListCombo.getSelectedItem();
        modelAuthor.addElement(selAuthor);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBookBtnActionPerformed
        Item newItem = new Item();
        newItem.setBarcode(barcodeField.getText());
        newItem.setTitle(titleField.getText());
        newItem.setReleaseYear(Year.of(Integer.parseInt(yearField.getText())).toString());
        newItem.setLocation(locationField.getText());
        newItem.setDescription(descField.getText());
        
        Book newBook = new Book();
        newBook.setItembarcode(barcodeField.getText());
        newBook.setIsbn(ISBNField.getText());
        newBook.setBookTypeId((BookType) bookTypeCombo.getSelectedItem());
        
        //Set all authors
        ArrayList<Author> authors = new ArrayList<>();
        int i = 0;
        while(i < modelAuthor.getSize()){
            authors.add(modelAuthor.getElementAt(i));
            i++;
        }
        
        newBook.setAuthorCollection(authors);
        
        //Set all tags
        ArrayList<Tag> tags = new ArrayList<>();
        int j = 0;
        while(j < modelTags.getSize()){
            tags.add(modelTags.getElementAt(j));
            j++;
        }
        
        newBook.setTagCollection(tags);
        try{
                //Save to database
            
                //Item
                this.getCardLayoutMain().getEntityManager().getTransaction().begin();
                this.getCardLayoutMain().getEntityManager().persist(newItem);
                this.getCardLayoutMain().getEntityManager().getTransaction().commit();
                
                //Book
                this.getCardLayoutMain().getEntityManager().getTransaction().begin();
                this.getCardLayoutMain().getEntityManager().persist(newBook);
                this.getCardLayoutMain().getEntityManager().getTransaction().commit();
                UI.showInfoDialog("Book saved");
                this.switchToCard(EmployeeStartUI.class);
            }catch (RollbackException | IllegalStateException e){
                UI.showErrorDialog("Could not save book to database");
            }
    }//GEN-LAST:event_saveBookBtnActionPerformed

    private void addTagBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTagBtnActionPerformed
        Tag selTag = (Tag) tagsListCombo.getSelectedItem();
        modelTags.addElement(selTag);
    }//GEN-LAST:event_addTagBtnActionPerformed

    private void tagsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tagsListMouseClicked
        //Remove element when double clicked
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            modelTags.removeElementAt(index);
        }
    }//GEN-LAST:event_tagsListMouseClicked

    private void authorsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authorsListMouseClicked
        //Remove element when double clicked
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            modelAuthor.removeElementAt(index);
        }
    }//GEN-LAST:event_authorsListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ISBNField;
    private javax.swing.JButton addTagBtn;
    private javax.swing.JComboBox authorListCombo;
    private javax.swing.JList<Author> authorsList;
    private javax.swing.JTextField barcodeField;
    private javax.swing.JComboBox bookTypeCombo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextArea descField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField locationField;
    private javax.swing.JButton saveBookBtn;
    private javax.swing.JList<Tag> tagsList;
    private javax.swing.JComboBox tagsListCombo;
    private javax.swing.JTextField titleField;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables
    DefaultListModel<Author> modelAuthor = new DefaultListModel<>();
    DefaultListModel<Tag> modelTags = new DefaultListModel<>();
}
