/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import entities.Item;
import entities.ItemLoan;
import entities.ItemLoanPK;
import entities.Loan;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Felix
 */
public class CreateLoanUI extends UI {
    private ArrayList<Item> itemsToLoad;
    
    public CreateLoanUI(CardLayoutMain cardLayoutMain) {
        super(cardLayoutMain);
        initComponents();
        initJlist();
        itemsToLoad = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        itemBarCodeField = new javax.swing.JTextField();
        addItemBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsList = new javax.swing.JList();
        createLoanBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("New loan");

        jLabel2.setText("Barcode");

        addItemBtn.setText("Add");
        addItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBtnActionPerformed(evt);
            }
        });

        itemsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(itemsList);

        createLoanBtn.setText("Create loan");
        createLoanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLoanBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Items to loan (double click to remove item)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(createLoanBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(itemBarCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addItemBtn))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itemBarCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addItemBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(createLoanBtn)
                        .addGap(109, 109, 109))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void initJlist(){
        model = new DefaultListModel<>();
        itemsList.setModel(model);
    }
    private void createLoanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLoanBtnActionPerformed
        ArrayList<Item> itemsToLoan = new ArrayList<Item>();
        int i = 0;
        while(i < model.getSize()){
            itemsToLoan.add(model.getElementAt(i));
            i++;
        }
        
        Loan loan = new Loan();
        loan.setPatronId(this.getCardLayoutMain().getPatronLoggedIn());
        loan.setCreated(new Date());

        try{
            //Save to database
            //Loan
            this.getCardLayoutMain().getEntityManager().getTransaction().begin();
            this.getCardLayoutMain().getEntityManager().persist(loan);
            this.getCardLayoutMain().getEntityManager().getTransaction().commit();
        }catch (RollbackException | IllegalStateException e){
            UI.showErrorDialog("Could not save loan to database");
            return;
        }
        
        //Set itemloans in database
        ArrayList<ItemLoan> itemLoans = new ArrayList<ItemLoan>();
        for(Item current : itemsToLoan){
            if(current.isOnLoan()){
                UI.showErrorDialog(current.getTitle()+" is alreay on loan. Remove it");
                return;
            }else{
                ItemLoan itemLoan = new ItemLoan();
                ItemLoanPK itemLoanPK = new ItemLoanPK(current.getBarcode(),loan.getLoanId());
                itemLoan.setItemLoanPK(itemLoanPK);
                itemLoan.setItem(current);
                itemLoan.setLoan(loan);
                this.getCardLayoutMain().getEntityManager().persist(itemLoan);
                itemLoans.add(itemLoan);
            }
        }
        
        try{
            //Save to database
            //ItemLoans
            this.getCardLayoutMain().getEntityManager().getTransaction().begin();
            loan.setItemLoanCollection(itemLoans);
            this.getCardLayoutMain().getEntityManager().getTransaction().commit();
        }catch (RollbackException | IllegalStateException e){
            UI.showErrorDialog("Could not save loan to database");
            return;
        }
        //Print receipt
        String receipt = "";
            
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Date newDate = new Date();

        receipt += "Name: "+ this.getCardLayoutMain().getPatronLoggedIn().getFullName()+"\n";
        receipt += "Loan date: "+ format.format(newDate)+"\n\n";
        for(ItemLoan current : itemLoans){
            receipt += current.getItem().getTitle()+"\n";
            
            //Check if book or dvd and calculate return date as appropriate
            if(current.getItem().getBook() == null){
                LocalDate returnDate = LocalDate.now().plusDays(7);
                Date finalDate = Date.from(returnDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
                
                receipt += "To be returned: "+format.format(finalDate)+" (7 days)";
            }else{
                int maxLoanDays = current.getItem().getBook().getBookTypeId().getLoanDays();
                LocalDate returnDate = LocalDate.now().plusDays(maxLoanDays);
                Date finalDate = Date.from(returnDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
                
                receipt += "To be returned: "+format.format(finalDate)+" ("+maxLoanDays+" days)";
            }
            receipt += "\n\n";
        }

        UI.showInfoDialog("Loan saved!\n\nThis is your receipt:\n"+receipt);
        
    }//GEN-LAST:event_createLoanBtnActionPerformed

    private void addItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtnActionPerformed
        List<Item> itemToAdd = this.getCardLayoutMain().getEntityManager().createNamedQuery("Item.findByBarcode").
                setParameter("barcode", itemBarCodeField.getText()).
                getResultList();
        if(!itemToAdd.isEmpty()){
            Item item = itemToAdd.get(0);
            if(item.isOnLoan()){
                UI.showErrorDialog("This is object is alreay on loan");
            }else{
                model.addElement(item);
            }
            
        }else{
            UI.showErrorDialog("There is no item with that barcode");
        }
    }//GEN-LAST:event_addItemBtnActionPerformed

    private void itemsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsListMouseClicked
        //Remove element when double clicked on
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            model.removeElementAt(index);
        }
    }//GEN-LAST:event_itemsListMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //Clear Jlist on show
        model.removeAllElements();
        
        //Add preloaded items
        for(Item current : this.getItemsToLoad()){
            model.addElement(current);
        }
        //Clear the list after loading it
        this.clearItemsToLoad();
        
    }//GEN-LAST:event_formComponentShown
    
    public ArrayList<Item> getItemsToLoad() {
        return itemsToLoad;
    }

    public void addItemsToLoad(Item item) {
        this.itemsToLoad.add(item);
    }
    public void clearItemsToLoad() {
        this.itemsToLoad.clear();
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemBtn;
    private javax.swing.JButton createLoanBtn;
    private javax.swing.JTextField itemBarCodeField;
    private javax.swing.JList itemsList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    DefaultListModel<Item> model = new DefaultListModel<>();
}
