package UI;

import entities.ItemLoan;
import entities.Loan;
import entities.Patron;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.RollbackException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import utils.RegexUtil;

public class PatronOverviewUI extends UI {
    /**
     * Creates new form PatronOverviewUI
     */
    public PatronOverviewUI(CardLayoutMain cardLayoutMain) {
        super(cardLayoutMain);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        overviewFirstname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        overviewLastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        overviewEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        overviewTele = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        overviewDob = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        overviewLoanList = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        overviewFullName = new javax.swing.JLabel();
        overviewChangeButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        newLoanBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        itemSrchBtn = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Firstname");

        overviewFirstname.setEnabled(false);

        jLabel2.setText("Lastname");

        overviewLastname.setEnabled(false);
        overviewLastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                overviewLastnameKeyPressed(evt);
            }
        });

        jLabel3.setText("Email");

        overviewEmail.setEnabled(false);

        jLabel4.setText("Telephone");

        overviewTele.setEnabled(false);

        jLabel5.setText("Birthday");

        overviewDob.setEnabled(false);

        jLabel6.setText("Loans");

        jScrollPane2.setViewportView(overviewLoanList);

        jScrollPane1.setViewportView(jList2);

        jLabel7.setText("Reservations");

        overviewFullName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        overviewChangeButton.setText("Change ");
        overviewChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewChangeButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Patron overview");

        newLoanBtn.setText("New loan");
        newLoanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLoanBtnActionPerformed(evt);
            }
        });

        logOutBtn.setText("Log out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        itemSrchBtn.setText("Item search");
        itemSrchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSrchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(overviewFullName)
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addContainerGap(293, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(overviewTele)
                        .addComponent(overviewEmail)
                        .addComponent(overviewLastname)
                        .addComponent(overviewFirstname)
                        .addComponent(overviewDob, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(overviewChangeButton)
                    .addComponent(logOutBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(itemSrchBtn)
                    .addComponent(newLoanBtn))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overviewFullName)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(overviewFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(overviewLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(overviewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(overviewTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(overviewDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overviewChangeButton)
                    .addComponent(itemSrchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logOutBtn)
                    .addComponent(newLoanBtn))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Patron loggedIn = this.getCardLayoutMain().getPatronLoggedIn();
        //Avsluta om inte inloggad
        if(loggedIn == null){
            UI.showErrorDialog("Not logged in!");
            System.exit(0);
        }
        
        //Populate data into textfields
        overviewFullName.setText(loggedIn.getFullName());
        
        overviewFirstname.setText(loggedIn.getFirstName());
        overviewLastname.setText(loggedIn.getLastName());
        overviewEmail.setText(loggedIn.getEmail());
        overviewTele.setText(loggedIn.getTelnr());
        //Format dob
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        overviewDob.setText(format.format(loggedIn.getDob()));
        
        EntityManager em = this.getCardLayoutMain().getEntityManager();
        DefaultListModel model = new DefaultListModel();
        overviewLoanList.setModel(model);
  
       
        List<Loan> asd = (List)this.getCardLayoutMain().getPatronLoggedIn().getLoanCollection();
        for(Loan current: asd){
            for(ItemLoan curr: current.getItemLoanCollection()){
                model.addElement(curr.getItem().getTitle());
            }
        }
        
        
        
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        
    }//GEN-LAST:event_formComponentHidden

    private void overviewLastnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_overviewLastnameKeyPressed
       
    }//GEN-LAST:event_overviewLastnameKeyPressed

    private void overviewChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewChangeButtonActionPerformed
        if(overviewChangeButton.getText().equals("Change")){
            overviewChangeButton.setText("Save");
            
            //Enable editing when button pushed
            overviewFirstname.setEnabled(true);
            overviewLastname.setEnabled(true);
            overviewEmail.setEnabled(true);
            overviewTele.setEnabled(true);
            //TODO: Fixed edit date
            //overviewDob.setEnabled(true);
        }else{
            //Save uppgifter when button clicked
            if(!RegexUtil.isValidEmail(overviewEmail.getText())){
                UI.showErrorDialog("Wrong email format");
            }else if(!RegexUtil.isValidFirstOrLastname(overviewFirstname.getText()) || !RegexUtil.isValidFirstOrLastname(overviewLastname.getText())){
                UI.showErrorDialog("Wrongt firstname or lastname format");
            }else if(!RegexUtil.isValidTelnr(overviewTele.getText())){
                UI.showErrorDialog("Wrong telephone format");
            }else{
                Patron loggedIn = this.getCardLayoutMain().getPatronLoggedIn();
                overviewChangeButton.setText("Change");
                
                this.getCardLayoutMain().getEntityManager().getTransaction().begin();
                overviewFirstname.setEnabled(false);
                loggedIn.setFirstName(overviewFirstname.getText());

                overviewLastname.setEnabled(false);
                loggedIn.setLastName(overviewLastname.getText());

                overviewEmail.setEnabled(false);
                loggedIn.setEmail(overviewEmail.getText());

                overviewTele.setEnabled(false);
                loggedIn.setTelnr(overviewTele.getText());
                //TODO: Save patron with new dob
                //overviewDob.setEnabled(false);
                //loggedIn.setDob(overviewFirstname.getText());

                try {
                    this.getCardLayoutMain().getEntityManager().getTransaction().commit();
                }catch (RollbackException e){
                    UI.showErrorDialog("Could not save to database");
                }
            }
        }
    }//GEN-LAST:event_overviewChangeButtonActionPerformed

    private void newLoanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLoanBtnActionPerformed
        switchToCard(CreateLoanUI.class);
    }//GEN-LAST:event_newLoanBtnActionPerformed

    private void itemSrchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSrchBtnActionPerformed
        switchToCard(ItemSearchUI.class);
    }//GEN-LAST:event_itemSrchBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        
        this.getCardLayoutMain().setPatronLoggedIn(null);
        UI.showInfoDialog("Bye, see you later!");
        switchToCard(StartPageUI.class);
                
    }//GEN-LAST:event_logOutBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton itemSrchBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton newLoanBtn;
    private javax.swing.JButton overviewChangeButton;
    private javax.swing.JTextField overviewDob;
    private javax.swing.JTextField overviewEmail;
    private javax.swing.JTextField overviewFirstname;
    private javax.swing.JLabel overviewFullName;
    private javax.swing.JTextField overviewLastname;
    private javax.swing.JList overviewLoanList;
    private javax.swing.JTextField overviewTele;
    // End of variables declaration//GEN-END:variables
}
