package UI;

import entities.Employee;
import entities.Patron;
import java.text.SimpleDateFormat;
import javax.persistence.RollbackException;
import javax.swing.JOptionPane;
import utils.RegexUtil;

public class PatronAdminUI extends UI {
    private Patron patron;
    public PatronAdminUI(CardLayoutMain cardLayoutMain) {
        super(cardLayoutMain);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        overviewFirstname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        overviewLastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        overviewEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        overviewTele = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        overviewDob = new javax.swing.JTextField();
        overviewFullName = new javax.swing.JLabel();
        overviewChangeButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Firstname");

        overviewFirstname.setEnabled(false);

        jLabel2.setText("Lastname");

        overviewLastname.setEnabled(false);

        jLabel3.setText("Email");

        overviewEmail.setEnabled(false);

        jLabel4.setText("Telephone");

        overviewTele.setEnabled(false);

        jLabel5.setText("Birthday");

        overviewDob.setEnabled(false);

        overviewFullName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        overviewChangeButton.setText("Change ");
        overviewChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewChangeButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Patron admin");

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Delete patron");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(overviewChangeButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(overviewTele)
                                    .addComponent(overviewEmail)
                                    .addComponent(overviewLastname)
                                    .addComponent(overviewFirstname)
                                    .addComponent(overviewDob, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(129, 129, 129)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deleteBtn)
                                    .addComponent(jLabel6)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(overviewFullName)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overviewFullName)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(overviewFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overviewLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overviewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overviewTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overviewDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(overviewChangeButton)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Employee loggedIn = this.getCardLayoutMain().getEmpLoggedIn();
        //Avsluta om inte inloggad
        if(loggedIn == null){
            UI.showErrorDialog("Not logged in!");
            System.exit(0);
        }
        
        //Populate data into textfields
        overviewFullName.setText(this.getPatron().getFullName());
        
        overviewFirstname.setText(this.getPatron().getFirstName());
        overviewLastname.setText(this.getPatron().getLastName());
        overviewEmail.setText(this.getPatron().getEmail());
        overviewTele.setText(this.getPatron().getTelnr());
        //Format dob
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        overviewDob.setText(format.format(this.getPatron().getDob()));
        
        
        
        
        
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        this.clearPatron();
    }//GEN-LAST:event_formComponentHidden

    private void overviewChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewChangeButtonActionPerformed
        if(overviewChangeButton.getText().equals("Change")){
            overviewChangeButton.setText("Save");
            
            //Enable editing when button pushed
            overviewFirstname.setEnabled(true);
            overviewLastname.setEnabled(true);
            overviewEmail.setEnabled(true);
            overviewTele.setEnabled(true);
            //TODO: Fixed edit date
            //overviewDob.setEnabled(true);
        }else{
            //Save uppgifter when button clicked
            if(!RegexUtil.isValidEmail(overviewEmail.getText())){
                UI.showErrorDialog("Wrong email format");
            }else if(!RegexUtil.isValidFirstOrLastname(overviewFirstname.getText()) || !RegexUtil.isValidFirstOrLastname(overviewLastname.getText())){
                UI.showErrorDialog("Wrongt firstname or lastname format");
            }else if(!RegexUtil.isValidTelnr(overviewTele.getText())){
                UI.showErrorDialog("Wrong telephone format");
            }else{
                Patron patronAdmin = this.getPatron();
                overviewChangeButton.setText("Change");
                
                this.getCardLayoutMain().getEntityManager().getTransaction().begin();
                overviewFirstname.setEnabled(false);
                patronAdmin.setFirstName(overviewFirstname.getText());

                overviewLastname.setEnabled(false);
                patronAdmin.setLastName(overviewLastname.getText());

                overviewEmail.setEnabled(false);
                patronAdmin.setEmail(overviewEmail.getText());

                overviewTele.setEnabled(false);
                patronAdmin.setTelnr(overviewTele.getText());
                //TODO: Save patron with new dob
                //overviewDob.setEnabled(false);
                //loggedIn.setDob(overviewFirstname.getText());

                try {
                    this.getCardLayoutMain().getEntityManager().getTransaction().commit();
                }catch (RollbackException e){
                    UI.showErrorDialog("Could not save to database");
                }
            }
        }
    }//GEN-LAST:event_overviewChangeButtonActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String[] options = {"Yes", "No"};
        int ans = JOptionPane.showOptionDialog(null, "Are you sure you want to delete "+patron.getFullName()+"?",
                "Click a button",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
        if(ans == 0){
            //Yes
            System.out.println("Yes");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    public Patron getPatron() {
        return patron;
    }

    public void setPatron(Patron patron) {
        this.patron = patron;
    }
    
    public void clearPatron() {
        this.patron = null;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton overviewChangeButton;
    private javax.swing.JTextField overviewDob;
    private javax.swing.JTextField overviewEmail;
    private javax.swing.JTextField overviewFirstname;
    private javax.swing.JLabel overviewFullName;
    private javax.swing.JTextField overviewLastname;
    private javax.swing.JTextField overviewTele;
    // End of variables declaration//GEN-END:variables
}
