package UI.EmployeeUI;

import UI.CardLayoutMain;
import UI.UI;
import entities.Employee;
import entities.Item;
import entities.ItemLoan;
import entities.Loan;
import entities.Patron;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.RollbackException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import utils.RegexUtil;

public class PatronAdminUI extends UI {
    private Patron patron;
    public PatronAdminUI(CardLayoutMain cardLayoutMain) {
        super(cardLayoutMain);
        initComponents();
    }
    DefaultListModel model = new DefaultListModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        overviewFirstname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        overviewLastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        overviewEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        overviewTele = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        overviewDob = new javax.swing.JTextField();
        overviewFullName = new javax.swing.JLabel();
        overviewChangeButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        passwordField2 = new javax.swing.JPasswordField();
        passwordField = new javax.swing.JPasswordField();
        backBtn = new javax.swing.JButton();
        retrnItemBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        loanList = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Firstname");

        overviewFirstname.setEnabled(false);

        jLabel2.setText("Lastname");

        overviewLastname.setEnabled(false);

        jLabel3.setText("Email");

        overviewEmail.setEnabled(false);

        jLabel4.setText("Telephone");

        overviewTele.setEnabled(false);

        jLabel5.setText("Birthday");

        overviewDob.setEnabled(false);

        overviewFullName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        overviewChangeButton.setText("Change ");
        overviewChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewChangeButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Patron admin");

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Delete patron");

        jLabel7.setText("New password");

        jLabel9.setText("Confirm password");

        passwordField2.setEditable(false);

        passwordField.setEditable(false);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        retrnItemBtn.setText("Return item");
        retrnItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrnItemBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(loanList);

        jLabel10.setText("Current loans");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(overviewTele)
                    .addComponent(overviewEmail)
                    .addComponent(overviewLastname)
                    .addComponent(overviewFirstname)
                    .addComponent(overviewDob, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(passwordField2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deleteBtn)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(128, 128, 128)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel10)))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(overviewChangeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(retrnItemBtn)
                        .addGap(46, 46, 46))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(overviewFullName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(overviewFullName)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(backBtn)))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(overviewFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(deleteBtn)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(overviewLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(overviewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(overviewTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(overviewDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overviewChangeButton)
                    .addComponent(retrnItemBtn))
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        EntityManager em = this.getCardLayoutMain().getEntityManager();
        em.clear();
        Employee loggedIn = this.getCardLayoutMain().getEmpLoggedIn();
        
        loanList.setModel(model);
        List<Loan> patronLoans = (List)this.getPatron().getLoanCollection();
        for(Loan current: patronLoans){
            for(ItemLoan curr: current.getItemLoanCollection()){
                if(curr.getReturned() == null){
                    model.addElement(curr.getItem());
                }
            }
        }
        //Populate data into textfields
        overviewFullName.setText(this.getPatron().getFullName());
        
        overviewFirstname.setText(this.getPatron().getFirstName());
        overviewLastname.setText(this.getPatron().getLastName());
        overviewEmail.setText(this.getPatron().getEmail());
        overviewTele.setText(this.getPatron().getTelnr());
        //Format dob
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        overviewDob.setText(format.format(this.getPatron().getDob()));
        passwordField.setText("");
        passwordField2.setText("");    
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        this.clearPatron();
        this.model.removeAllElements();
    }//GEN-LAST:event_formComponentHidden

    private void overviewChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewChangeButtonActionPerformed
        if(overviewChangeButton.getText().equals("Change")){
            overviewChangeButton.setText("Save");
            
            //Enable editing when button pushed
            overviewFirstname.setEnabled(true);
            overviewLastname.setEnabled(true);
            overviewEmail.setEnabled(true);
            overviewTele.setEnabled(true);
            passwordField.setEditable(true);
            passwordField2.setEditable(true);
            //TODO: Fixed edit date
            //overviewDob.setEnabled(true);
        }else{
            //Save uppgifter when button clicked
            if(!RegexUtil.isValidEmail(overviewEmail.getText())){
                UI.showErrorDialog("Wrong email format");
            }else if(!RegexUtil.isValidFirstOrLastname(overviewFirstname.getText()) || !RegexUtil.isValidFirstOrLastname(overviewLastname.getText())){
                UI.showErrorDialog("Wrongt firstname or lastname format");
            }else if(!RegexUtil.isValidTelnr(overviewTele.getText())){
                UI.showErrorDialog("Wrong telephone format");
            }else if(passwordField.getPassword().length > 0 && (passwordField.getPassword() != passwordField2.getPassword() && passwordField.getPassword().length < 6)){
                UI.showErrorDialog("Password does not match or is less then 6 characters");
            }else{
                Patron patronAdmin = this.getPatron();
                overviewChangeButton.setText("Change");
                
                this.getCardLayoutMain().getEntityManager().getTransaction().begin();
                overviewFirstname.setEnabled(false);
                patronAdmin.setFirstName(overviewFirstname.getText());

                overviewLastname.setEnabled(false);
                patronAdmin.setLastName(overviewLastname.getText());

                overviewEmail.setEnabled(false);
                patronAdmin.setEmail(overviewEmail.getText());

                overviewTele.setEnabled(false);
                patronAdmin.setTelnr(overviewTele.getText());
                
                passwordField.setEditable(false);
                passwordField2.setEditable(false);
                
                if(passwordField.getPassword().length > 0){
                    patronAdmin.setPassword(new String(passwordField.getPassword()));
                }
                
                //TODO: Save patron with new dob
                //overviewDob.setEnabled(false);
                //loggedIn.setDob(overviewFirstname.getText());

                try {
                    this.getCardLayoutMain().getEntityManager().getTransaction().commit();
                }catch (RollbackException e){
                    UI.showErrorDialog("Could not save to database");
                }
            }
        }
    }//GEN-LAST:event_overviewChangeButtonActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String[] options = {"Yes", "No"};
        int ans = JOptionPane.showOptionDialog(null, "Are you sure you want to delete "+patron.getFullName()+"?",
                "Click a button",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
        if(ans == 0){
            //TODO: Implement
            //Yes
            System.out.println("Yes");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.switchToCard(PatronSearchUI.class);
    }//GEN-LAST:event_backBtnActionPerformed

    private void retrnItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrnItemBtnActionPerformed
        
        Item returnItem = (Item)model.get(loanList.getSelectedIndex());
        
        List<ItemLoan> itemLoans = (List<ItemLoan>)returnItem.getItemLoanCollection();
        for(ItemLoan current: itemLoans){
            if(current.getReturned() == null){
                current.setReturned(new Date());
                UI.showInfoDialog(current.getItem().getTitle()+" är nu återlämnad!");
            }
        }
       
      
    }//GEN-LAST:event_retrnItemBtnActionPerformed

    public Patron getPatron() {
        return patron;
    }

    public void setPatron(Patron patron) {
        this.patron = patron;
    }
    
    public void clearPatron() {
        this.patron = null;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> loanList;
    private javax.swing.JButton overviewChangeButton;
    private javax.swing.JTextField overviewDob;
    private javax.swing.JTextField overviewEmail;
    private javax.swing.JTextField overviewFirstname;
    private javax.swing.JLabel overviewFullName;
    private javax.swing.JTextField overviewLastname;
    private javax.swing.JTextField overviewTele;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField passwordField2;
    private javax.swing.JButton retrnItemBtn;
    // End of variables declaration//GEN-END:variables
}
